### ISSUE TITLE
stc quantity is not visible. String format is incorrect.

### ISSUE THREAD

**Issue by ysinyldz** [Elements-Studio/starswap-bug-bounty#1]
You can see issue at the link below

[https://i.hizliresim.com/6zybrjk.png](url)

**Comment by 9191stc** [comment]
Make sure your system language or page encoding is correct?

**Comment by ysinyldz** [comment]
System lang is Turkish but i dont understand encoding thing...

21 Şub 2022 Pzt 05:47 tarihinde 9191stc ***@***.***> şunu
yazdı:

**Comment by GravitateX** [comment]
Image can not be seen.

**Comment by ysinyldz** [comment]
[image: image.png]

Paradis Sivers ***@***.***>, 23 Şub 2022 Çar, 06:19 tarihinde
şunu yazdı:
