### ISSUE TITLE
质押获取不到STAR余额

### ISSUE THREAD

**Issue by Foorgoo** [Elements-Studio/starswap-bug-bounty#2]
钱包余额有STAR，但是质押获取不到，无法质押
![1](https://user-images.githubusercontent.com/85097010/154647476-ba8e8729-bc24-4a36-86a7-72347702f4fb.png)

**Comment by GravitateX** [comment]
New STAR token address: 
```
0x8c109349c6bd91411d6bc962e080c4a3::STAR::STAR
```
@Foorgoo
