### ISSUE TITLE
Stake issues

### ISSUE THREAD

**Issue by jefferdex** [Elements-Studio/starswap-bug-bounty#4]
So hard to click on stake when using mobile phone on desktop mode site. 

Fixed it as soon as possible.

Aside from that i have a very wonderful experience during the testnet.

0x2E4B20E13Ae7E5c4dfe4932727356043

**Comment by GravitateX** [comment]
Destkop computer and Chrome are recommended to use Starmask and Starswap

**Comment by jefferdex** [comment]
Nice job
Nice teams
Nice project

Awesome and amazing project
Keep it rolling
